name: learn-github-action
run-name: ${{ github.actor }} is learning Github Actions
on: 
 # push: # Uncomment to run on every push
  workflow_dispatch:
    
jobs:
  test:
    name: Test index output variable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: Run command
      run : node index.js
      env: 
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
